import PDFDocument from "pdfkit";
import { BulkInventory, Buyback, Expense, PaymentEntry, Repair, Sale, SerializedInventory, Store, StoreInventory } from "../../db/models.js";
import { HttpError } from "../../utils/httpError.js";

function buildDateRange(rangeKey, from, to) {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const map = {
    today: [today, today],
    yesterday: [new Date(today.getTime() - 86400000), new Date(today.getTime() - 86400000)],
    this_week: [new Date(today.getTime() - (today.getDay() || 7 - 1) * 86400000), today],
    this_month: [new Date(today.getFullYear(), today.getMonth(), 1), today],
    last_month: [new Date(today.getFullYear(), today.getMonth() - 1, 1), new Date(today.getFullYear(), today.getMonth(), 0)],
  };
  if (rangeKey === "custom") {
    if (!from || !to) throw new HttpError(400, "Custom date range requires from/to", "REPORT_RANGE_REQUIRED");
    return [new Date(from), new Date(to)];
  }
  return map[rangeKey] || map.this_month;
}

export async function getAdminReportOverview(filters) {
  const [start, endRaw] = buildDateRange(filters.quickRange, filters.fromDate, filters.toDate);
  const end = new Date(endRaw); end.setHours(23, 59, 59, 999);
  const storeQuery = filters.storeIds?.length ? { store: { $in: filters.storeIds } } : {};
  const dateQuery = { createdAt: { $gte: start, $lte: end } };
  const [stores, sales, repairs, buybacks, expenses, payments, inventories, bulkInventory, serializedInventory] = await Promise.all([
    Store.find({ isActive: true }).lean(),
    Sale.find({ ...storeQuery, ...dateQuery }).lean(),
    Repair.find({ ...storeQuery, ...dateQuery }).lean(),
    Buyback.find({ ...storeQuery, ...dateQuery }).lean(),
    Expense.find({ ...storeQuery, ...dateQuery }).lean(),
    PaymentEntry.find({ ...storeQuery, ...dateQuery }).lean(),
    StoreInventory.find(storeQuery).populate("items.product").lean(),
    BulkInventory.find(storeQuery).populate("product").lean(),
    SerializedInventory.find({ ...storeQuery, status: "in_stock" }).populate("product").lean(),
  ]);
  const totalSales = sales.reduce((s, x) => s + Number(x.grandTotal || 0), 0);
  const totalRepairs = repairs.reduce((s, x) => s + Number(x.inCash || 0) + Number(x.inOnline || 0), 0);
  const totalExpenses = expenses.reduce((s, x) => s + Number(x.outCash || 0) + Number(x.outOnline || 0), 0);
  const totalBuyback = buybacks.reduce((s, x) => s + Number(x.cashAmount || 0) + Number(x.onlineAmount || 0), 0);
  const bulkValue = bulkInventory.reduce((sum, item) => sum + (Number(item.quantity || 0) * Number(item.product?.unitPrice || 0)), 0);
  const serializedValue = serializedInventory.reduce((sum, item) => sum + Number(item.product?.unitPrice || 0), 0);
  const legacyValue = bulkInventory.length || serializedInventory.length
    ? 0
    : inventories.reduce((sum, inv) => sum + inv.items.reduce((a, it) => a + (Number(it.quantity || 0) * Number(it.product?.unitPrice || 0)), 0), 0);
  const inventoryValue = bulkValue + serializedValue + legacyValue;
  return {
    filters: { ...filters, fromDate: start, toDate: end },
    kpis: { totalSales, totalRepairs, totalExpenses, totalBuyback, inventoryValue, net: totalSales + totalRepairs - totalExpenses - totalBuyback },
    counts: { sales: sales.length, repairs: repairs.length, buybacks: buybacks.length, expenses: expenses.length, payments: payments.length, stores: stores.length },
  };
}

export async function streamReportPdf(res, payload, meta) {
  const doc = new PDFDocument({ size: "A4", margin: 36 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="admin_report_${Date.now()}.pdf"`);
  doc.pipe(res);
  doc.fontSize(18).text("Quality Mobiles - Admin Report", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Generated By: ${meta.username} | Generated At: ${new Date().toISOString()}`);
  doc.text(`Store Scope: ${meta.storeLabel}`);
  doc.moveDown();
  doc.fontSize(13).text("Summary");
  const { kpis, counts } = payload;
  doc.fontSize(10).text(`Sales Revenue: Rs ${kpis.totalSales.toFixed(2)}`);
  doc.text(`Repair Revenue: Rs ${kpis.totalRepairs.toFixed(2)}`);
  doc.text(`Buyback Outflow: Rs ${kpis.totalBuyback.toFixed(2)}`);
  doc.text(`Expenses: Rs ${kpis.totalExpenses.toFixed(2)}`);
  doc.text(`Inventory Value: Rs ${kpis.inventoryValue.toFixed(2)}`);
  doc.text(`Net Position: Rs ${kpis.net.toFixed(2)}`);
  doc.moveDown();
  doc.fontSize(13).text("Operational Counts");
  Object.entries(counts).forEach(([k, v]) => doc.fontSize(10).text(`${k}: ${v}`));
  doc.moveDown();
  doc.fontSize(9).text("Page 1", { align: "right" });
  doc.end();
}
