import { Product, StoreInventory } from "../../db/models.js";
import { HttpError } from "../../utils/httpError.js";

// Job Numbers are allocated by the system when an inventory/product record is
// created (see utils/jobNumber.js) and stay with that record for its whole
// lifecycle. Nothing here assigns or clears one — these endpoints exist only
// to read a record back by its number.

const IMMUTABLE_MESSAGE =
  "Job numbers are generated by the system and cannot be changed or removed";

/**
 * Kept so callers of the old manual-linking API get a clear answer instead of
 * a 404. Job numbers are no longer entered by hand.
 */
export async function linkJobNumberToProduct() {
  throw new HttpError(409, IMMUTABLE_MESSAGE, "JOB_NUMBER_IMMUTABLE");
}

export async function unlinkJobNumber() {
  throw new HttpError(409, IMMUTABLE_MESSAGE, "JOB_NUMBER_IMMUTABLE");
}

function requireJobNumber(jobNumber) {
  const trimmed = String(jobNumber || "").trim();
  if (!trimmed) {
    throw new HttpError(400, "Job number cannot be empty", "INVALID_JOB_NUMBER");
  }
  return trimmed;
}

/**
 * Match on both identifier fields: `jobId` is where the generated number
 * lives, `jobNumber` is the legacy column some older records still carry.
 * Sales lookup matches the same pair, so POS and this endpoint agree.
 */
function jobNumberQuery(jobNumber) {
  return { $or: [{ jobId: jobNumber }, { jobNumber }] };
}

/**
 * Fetch product by job number
 */
export async function getProductByJobNumber(jobNumber) {
  const trimmed = requireJobNumber(jobNumber);

  const product = await Product.findOne({
    ...jobNumberQuery(trimmed),
    isActive: true,
  }).lean();

  if (!product) return null;

  return {
    id: product._id,
    sku: product.sku,
    name: product.name,
    category: product.category,
    unit_price: product.unitPrice,
    tax_rate: product.taxRate,
    job_number: product.jobId || product.jobNumber,
  };
}

/**
 * Search inventory by job number across all stores
 */
export async function searchInventoryByJobNumber(jobNumber) {
  const trimmed = requireJobNumber(jobNumber);

  // Find product(s) with this job number
  const products = await Product.find({ ...jobNumberQuery(trimmed), isActive: true })
    .select("_id jobId jobNumber")
    .lean();
  const productIds = products.map((p) => p._id);

  const inventoryDocs = await StoreInventory.find({
    $or: [
      { "items.jobNumber": trimmed },
      { "items.product": { $in: productIds } },
    ],
  }).lean();

  const results = [];
  for (const doc of inventoryDocs) {
    for (const item of doc.items) {
      if (item.jobNumber === trimmed || productIds.some((id) => id.equals(item.product))) {
        results.push({
          store_id: doc.store,
          product_id: item.product,
          quantity: item.quantity,
          reserved_quantity: item.reservedQuantity,
          job_number: item.jobNumber || trimmed,
        });
      }
    }
  }

  return results.sort((a, b) => String(a.store_id).localeCompare(String(b.store_id)));
}
